const defaultDishes=[
 {id:1,name:"鲜虾蒸蛋",category:"荤菜",meal:"breakfast",desc:"嫩滑蒸蛋 · 鲜虾 · 葱花",rating:"4.9",image:"https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80"},
 {id:2,name:"番茄牛腩面",category:"主食",meal:"lunch",desc:"番茄 · 牛腩 · 手擀面",rating:"5.0",image:"https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=800&q=80"},
 {id:3,name:"清炒时蔬",category:"素菜",meal:"lunch",desc:"时令蔬菜 · 蒜蓉 · 少油",rating:"4.8",image:"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80"},
 {id:4,name:"山药排骨汤",category:"汤羹",meal:"dinner",desc:"山药 · 排骨 · 枸杞",rating:"4.9",image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80"},
 {id:5,name:"香煎三文鱼",category:"荤菜",meal:"dinner",desc:"三文鱼 · 柠檬 · 黑胡椒",rating:"4.9",image:"https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=80"},
 {id:6,name:"南瓜小米粥",category:"主食",meal:"breakfast",desc:"南瓜 · 小米 · 红枣",rating:"4.7",image:"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80"}
];
let dishes=JSON.parse(localStorage.getItem("familyDishes")||"null")||defaultDishes;
let orders=JSON.parse(localStorage.getItem("familyOrders")||"[]"), currentMeal="breakfast", category="全部";
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function save(){localStorage.setItem("familyDishes",JSON.stringify(dishes));localStorage.setItem("familyOrders",JSON.stringify(orders))}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2500)}
function dishCard(d,meal=false){const ordered=orders.some(o=>o.dishId===d.id&&o.meal===currentMeal&&o.date==="2026-08-20");return `<article class="dish-card meal-card"><img class="dish-image" src="${d.image}" alt="${d.name}"><div class="meal-info"><h3>${d.name}</h3><p>${d.desc||d.ingredients||"婆婆的家常味道"}</p><div class="card-bottom"><span class="rating">★ ${d.rating||"新菜"}</span>${meal?`<button class="order-btn ${ordered?"ordered":""}" data-order="${d.id}">${ordered?"已点入菜单":"点这道菜"}</button>`:""}</div></div></article>`}
function renderMeals(){const list=dishes.filter(d=>d.meal===currentMeal);$("#mealCards").innerHTML=list.length?list.map(d=>dishCard(d,true)).join():'<p class="hero-copy">这顿还没有安排菜品，去菜单里挑一道吧。</p>'}
function renderMenu(){const q=$("#searchInput").value.toLowerCase();const list=dishes.filter(d=>(category==="全部"||d.category===category)&&`${d.name}${d.desc}${d.ingredients||""}`.toLowerCase().includes(q));$("#allDishes").innerHTML=list.map(d=>dishCard(d)).join("")||"<p>还没有找到这道菜。</p>"}
function renderRecords(){const list=orders.slice().reverse();$("#weekCount").textContent=list.length;const counts={};list.forEach(o=>counts[o.name]=(counts[o.name]||0)+1);$("#favoriteDish").textContent=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||"—";$("#recordsList").innerHTML=list.length?list.map(o=>`<div class="record"><img src="${o.image}" alt=""><div><strong>${o.name}</strong><p>${o.meal==="breakfast"?"早餐":o.meal==="lunch"?"午餐":"晚餐"} · ${o.rating?"已点评":"等待点评"}</p></div><time>${o.date}</time>${!o.rating?`<button class="text-btn" data-rate="${o.id}">去点评</button>`:""}</div>`).join(""):"<p class='hero-copy'>还没有点菜记录，今天就开始吧。</p>"}
function renderAdmin(){ $("#adminTable").innerHTML=dishes.map(d=>`<tr><td><strong>${d.name}</strong></td><td>${d.category}</td><td><span class="status">已上架</span></td><td>2026.08.20</td><td><button class="text-btn" data-remove="${d.id}">下架</button></td></tr>`).join("")}
function showView(view){$$(".view").forEach(v=>v.classList.toggle("active",v.id===`${view}View`));$$("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view));window.scrollTo({top:0,behavior:"smooth"})}
function openModal(){$("#dishModal").classList.add("open")}
document.addEventListener("click",e=>{const view=e.target.closest("[data-view]");if(view){e.preventDefault();showView(view.dataset.view);if(view.dataset.view==="menu")renderMenu();if(view.dataset.view==="records")renderRecords();if(view.dataset.view==="admin")renderAdmin()}const meal=e.target.closest("[data-meal]");if(meal){currentMeal=meal.dataset.meal;$$(".meal-tab").forEach(b=>b.classList.toggle("active",b===meal));renderMeals()}const order=e.target.closest("[data-order]");if(order){const d=dishes.find(x=>x.id==order.dataset.order);const existing=orders.findIndex(o=>o.dishId===d.id&&o.meal===currentMeal&&o.date==="2026-08-20");if(existing>=0){orders.splice(existing,1);toast("已从今日菜单移除")}else{orders.push({id:Date.now(),dishId:d.id,name:d.name,image:d.image,meal:currentMeal,date:"2026-08-20"});toast("已点入今日菜单，婆婆会看到的 ♡")}save();renderMeals()}if(e.target.matches("#openAddDish,#openAddDishAdmin"))openModal();if(e.target.matches("[data-close]")||e.target=== $("#dishModal"))$("#dishModal").classList.remove("open");const remove=e.target.closest("[data-remove]");if(remove){dishes=dishes.filter(d=>d.id!=remove.dataset.remove);save();renderAdmin();toast("菜品已下架")}const rate=e.target.closest("[data-rate]");if(rate){const o=orders.find(x=>x.id==rate.dataset.rate);o.rating=5;save();renderRecords();toast("感谢你的 5 星点评！")}});$("#searchInput").addEventListener("input",renderMenu);$$(".chip").forEach(c=>c.addEventListener("click",()=>{$$(".chip").forEach(x=>x.classList.remove("active"));c.classList.add("active");category=c.dataset.category;renderMenu()}));
$("#dishForm").addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target),file=f.get("image");const add=image=>{dishes.unshift({id:Date.now(),name:f.get("name"),category:f.get("category"),meal:"dinner",ingredients:f.get("ingredients"),desc:f.get("ingredients"),method:f.get("method"),rating:"新菜",image:image||defaultDishes[0].image});save();e.target.reset();$("#dishModal").classList.remove("open");renderMenu();renderAdmin();toast("新菜已加入家庭菜单")};if(file?.size){const reader=new FileReader();reader.onload=()=>add(reader.result);reader.readAsDataURL(file)}else add()});
renderMeals();renderMenu();renderRecords();renderAdmin();
